import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { MenuProvider } from "@/context/menuContext";
import { AuthProvider } from "@/context/authContext";

// 1. Set up the Inter font with a CSS variable
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      {/* 2. Apply the Inter font variable to the body */}
      <body
        className={`${inter.variable} font-sans antialiased`}
      >
        <div className="absolute top-4 right-4 z-50">
        </div>
            <AuthProvider>
              <MenuProvider>
                {children}
              </MenuProvider>
            </AuthProvider>
      </body>
    </html>
  );
}